// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaoWaE11vcRdH8AhSyU5IEyF_cN75iXYg',
    appId: '1:712735823459:web:9c6dd2530ce13f0830ca56',
    messagingSenderId: '712735823459',
    projectId: 'fir-task-648a0',
    authDomain: 'fir-task-648a0.firebaseapp.com',
    storageBucket: 'fir-task-648a0.appspot.com',
    measurementId: 'G-72MWFJTNZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvX2XihC9OgPtR3Nd0-gs1Er0hIqkaMBQ',
    appId: '1:712735823459:android:09cfe073c139766c30ca56',
    messagingSenderId: '712735823459',
    projectId: 'fir-task-648a0',
    storageBucket: 'fir-task-648a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcEwF452wznaYiH_f24Ftm-96qP401YgE',
    appId: '1:712735823459:ios:790f417a33adee1730ca56',
    messagingSenderId: '712735823459',
    projectId: 'fir-task-648a0',
    storageBucket: 'fir-task-648a0.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcEwF452wznaYiH_f24Ftm-96qP401YgE',
    appId: '1:712735823459:ios:790f417a33adee1730ca56',
    messagingSenderId: '712735823459',
    projectId: 'fir-task-648a0',
    storageBucket: 'fir-task-648a0.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaoWaE11vcRdH8AhSyU5IEyF_cN75iXYg',
    appId: '1:712735823459:web:e96449fdb66d77e330ca56',
    messagingSenderId: '712735823459',
    projectId: 'fir-task-648a0',
    authDomain: 'fir-task-648a0.firebaseapp.com',
    storageBucket: 'fir-task-648a0.appspot.com',
    measurementId: 'G-JYJHDWSNYW',
  );

}